terms:
  - "experiencia"
  - "usuario"
  - "interface"
  - "usabilidade"
  - "interacao"
  - "sistema"
  - "ergonomia"
  - "digital"
  - "informacao"
  - "tecnologia"

max_pages: 10

repos:
  estudos_em_design: estudos_em_design
  infodesign: infodesign
  human_factors_in_design: human_factors_in_design
  arcos_design: arcos_design
  design_e_tecnologia: design_e_tecnologia
  triades: triades
  educacao_grafica: educacao_grafica

csv_filename: "data/raw/search_results.csv"

data_processing:
  transformed_results: "data/processed/transformed_results.csv"
  enable_auto_transform: true

curation:
  curation_candidates: "data/processed/curation_candidates.csv"
  enable_auto_filtering: true

deduplication:
  base_database: "data/raw/base_database.csv"
  new_records_output: "data/processed/new_records.csv"
  enable_auto_dedup: true